### PR TITLE
Create taiga.js

### PR DESCRIPTION
**Pull request by matthewbdaly**
Added an integration for Taiga (https://taiga.io/)

### CODE REVIEW

**Comment by dtschust** [comment]
Hey @matthewbdaly, thanks for taking the time to make a PR! I hadn't heard of Taiga but I love more integrations :tada:. A couple of requests:

* Could you add a screenshot of an example bug as shown in Taiga's API to the `.github` folder? I can handle adding the documentation to `integrations.md` but I'd appreciate not having to create a demo Taiga account if you've already got one.
* It looks like Taiga supports a lot of fields for bug creation [(docs here)](https://taigaio.github.io/taiga-doc/dist/api.html#issues-create). Would it possible for the description to be a little more human readable, [as done in the github integration](https://github.com/dtschust/redux-bug-reporter/blob/master/src/integrations/github.js#L20)?

If you don't have time to make those changes please let me know and I can plan to merge this as is, something is certainly better than nothing!

**Comment by matthewbdaly** [comment]
I'd be happy to add those changes, but I won't be able to get a screenshot until early next week. I can possibly add the changes to the fields in the next couple of days. I can either open another PR for those changes in a few days or sit on this one till I can add them.

**Comment by dtschust** [comment]
Great! Let's sit on these changes for now and if I've got time this weekend to get the screenshot and change the fields I'll take a crack at it. If I get it working I'll merge this PR in as is and then work on top of it. Thanks again!

**Comment by dtschust** [comment]
@matthewbdaly I was able to add documentation and change the formatting of the bug slightly, so I'm going to merge this in and then push those changes in on top of it. Thanks again!

**Comment by matthewbdaly** [comment]
Ok. I may be able to add a screenshot in the next few days - if so I'll submit another pull request with it.

**Comment by dtschust** [comment]
Just added screenshots here: https://github.com/dtschust/redux-bug-reporter/blob/master/docs/integrations.md

**Comment by matthewbdaly** [comment]
Ok, cheers for letting me know! The project I'm using this on is still in heavy development so I'm happy to give it a test on thtm

**Pull request merged**
