### PR TITLE
#1: Added Immutable support

### PR DESCRIPTION
**Pull request by RamonGebben**
This resolves my question from #1.

### CODE REVIEW

**Comment by dtschust** [comment]
Woah, thanks for the PR @RamonGebben ! I think what I'd prefer to do is solve this issue more generically, probably with `customEncode`/`customDecode` hooks when submitting a bug and playing the bug back, and adding documentation for Immutable specifically and a more generic case. This would also mean this package wouldn't depend on a specific immutable implementation in case another library gains popularity as well.
If I'm understanding your PR correctly the bug would still file incorrectly, because the redux store state would still be an immutable object instead of JSON. I'll try to get a PR up in the next few days with the approach described above and tag you in it to see if it suits your needs. Thanks for the contribution!

**Comment by dtschust** [comment]
@RamonGebben Not quite ready to merge (still need to add documentation, unit tests and a little cleanup), but this is what I was thinking https://github.com/dtschust/redux-bug-reporter/commit/1927bc4bbf883de85a6859bd81d18d03635332ce#diff-0e1416c3630b13806b2a322907ec4f3e . All you would need to do for immutable is add a customDecode function similar to this:
```jsx
const customDecode = (state) => {
  return { input: fromJS(state.input) }
}
```

**Comment by RamonGebben** [comment]
@dtschust Indeed that would suffice and an elegant solution. When would this be ready to merge?

**Comment by dtschust** [comment]
I'll try and get it done this weekend, if you want to play with it beforehand feel free to point to that branch directly in your package.json, i'd love any feedback!

**Comment by dtschust** [comment]
Just merged a fix, will publish to npm later today!

**Comment by kriskate** [comment]
Hey guys, I had the same issue, using immutable stores.
My solution was to have a local copy of redux-bug-reporter.js and added a new prop "storeWork", which I would pass when initialising the ReduxBugReporter component.

Now, inside the bugReporterPlayback method, I use that callback in order to "set my store straight", like so:
```javascript
    if(this.props.storeWork) {
      initialState = this.props.storeWork(initialState)
      finalState = this.props.storeWork(finalState)
    }
```
and parse those inside the actual storeWork method. 
Otherwise, I wouldn't be able to use the data received from the bug reporter in my app.

This way, you can use any kind of store alteration you want, not only immutatability.

**Comment by kriskate** [comment]
sorry, just seen that that's what customDecode does as well... switched to using that and passing my storeWork method to it

```javascript
const storeWork = store => {
  if(!Immutable.Iterable.isIterable(store.myStore))
    store.myStore = Immutable.Map(store.myStore)

  return store
}
```

**Comment by dtschust** [comment]
Glad to hear that `customDecode` worked for your needs @kriskate , thanks for sharing!

**Pull request closed without merging**
