### PR TITLE
Fixed setting of NODE_ENV in package.json to be Windows compatible

### PR DESCRIPTION
**Pull request by larsw**
What the title says. "SET ENV_VARIABLE" works on both windows & in linux/unix shells.

### CODE REVIEW

**Comment by dtschust** [comment]
Thanks for submitting this PR! Have you used the `cross-env` npm package before? I think I would prefer to use it instead but would happily merge a PR from you if you used it! The redux package itself uses it https://github.com/reactjs/redux/blob/master/package.json

Thanks again!

**Comment by larsw** [comment]
Hi,

No I have not. If you merge this PR, I can look into it and submit another request.

**Comment by dtschust** [comment]
Ok, I'd like to publish a version to npm today with the cross-env implementation. So I'll merge this PR shortly along with a few other PRs, then merge a cross-env PR, then publish to npm. This way you'll still get contribution credit because I appreciate you making a PR, but no published npm version will have the code in this PR. Sound good?

**Comment by larsw** [comment]
Thanks.

**Pull request merged**
